=== dwew2/hcwl/search/HCWL Sketchengine/sketchengine.dtd
<!ELEMENT head (#PCDATA | lb)*>
<!ELEMENT pb (#PCDATA | head | lb)*>
<!ATTLIST pb n CDATA #IMPLIED>
<!ELEMENT lb (#PCDATA | head | lb)*>
<!ATTLIST lb n CDATA #IMPLIED>
<!ELEMENT text (#PCDATA | pb | text | head)*>
<!ATTLIST text id CDATA #IMPLIED>

=== dwew2/hcwl/search/corpora/dpo_ske.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE text SYSTEM "../sketchengine.dtd" [
<!ENTITY % Conc SYSTEM "../dtds/conc.ent">
<!-- %Conc; -->
<!ENTITY % TEI.extensions.ent SYSTEM "../dtds/hcwl.ent">
%TEI.extensions.ent;
<!ENTITY % TEI.extensions.dtd SYSTEM "../dtds/hcwl.dtd">
%TEI.extensions.dtd;
<!ENTITY % TEI.prose 'INCLUDE'>
<!ENTITY % TEI.linking 'INCLUDE'>
<!ENTITY % TEI.figures 'INCLUDE'>
<!ENTITY % TEI.analysis 'INCLUDE'>
<!ENTITY % TEI.XML 'INCLUDE'>
<!ENTITY % ISOlat1 SYSTEM "../dtds/iso-lat1.ent">
%ISOlat1;
<!ENTITY % ISOlat2 SYSTEM "../dtds/iso-lat2.ent">
%ISOlat2;
<!ENTITY % ISOnum SYSTEM "../dtds/iso-num.ent">
%ISOnum;
<!ENTITY % ISOpub SYSTEM "../dtds/iso-pub.ent">
%ISOpub;
]>

<text id="DPO">
   <text id="DPO">
      
      
      <pb n="64.">
      
      
      
      <head>
       
      <lb n="13">PEN. IV.</lb>
      </head>
      
      
      
      
      
      
       
      <lb n="14">Yr achos y galwyd y Saeson i Frydain. Llythyr
      </lb> 
      <lb n="15">y Brutaniaid attynt. Hwythau'n dyfod yn 
      </lb>
      <lb n="15-16">ewyllysgar,
      </lb>
      <lb n="16">
       ac ym mhen yspaid yn troi'n fradwyr.
      </lb> 
      <lb n="17">Y Brutaniaid a'r hynny yn eu hymlid hwy 
      </lb>
      <lb n="17-18">adref.
      </lb>
      <lb n="18">
      &nbsp;Rhonwen y Saesones yn gwenwyno 
      </lb>
      <lb n="18-19">Gwrthefyr
      </lb>
      <lb n="19">
       fendigaid y Brenin. A'r Saeson a'r 
      </lb>
      <lb n="19-20">hynny
      </lb>
      <lb n="20">
       yn dyfod drachefn i Frydain. Twyll y 
      </lb>
      <lb n="20-21">Cyllill
      </lb>
      <lb n="21">
       hirion. Marwolaeth echryslawn y brenin
      </lb> 
      <lb n="22">Gwrtheyrn. Y Saeson yn myned adref o'i gwir
      </lb> 
      <lb n="23">fodd, Ac yn cael groesaw hagr a'r eu 
      </lb>
      <lb n="23-24">dyfodiad
      </lb>
      <lb n="24">
       eilwaith. Lladd Hengist eu Tywysog. 
      </lb>
      <lb n="24-25">Gosod
      </lb>
      <lb n="25">
       cebystr am wddf pob Sais. Gwrthryfel 
      </lb>
      <lb n="25-26">Pasgen.
      </lb>
      <lb n="26">
       Sais yn gwenwyno Emrys wledig y Brenin.
      </lb> 
      <lb n="27">Y Drwg a wnaethpwyd ganddynt a'r hynny, ac
      </lb> 
      <lb n="28">yn cael eu hymlid gan Uthr Bendragon. 
      </lb>
      <lb n="28-29">Anghyttundeb
      </lb>
      <lb n="29">
       ym mysc y Brutaniaid eu hun. Dynion
      
      
      </lb>
      </pb>
      <pb n="65.">
      
      
       
      <lb n="1">drwg yn eu chwerwder yn gollwng Swyddogion
      </lb> 
      <lb n="2">y Saeson yn rhyddion o'r Carchar, a hwythau
      </lb> 
      <lb n="3">yn myned i Germani i godi gwyr. Yr 
      </lb>
      <lb n="3-4">ymddiddan
      </lb>
      <lb n="4">
       a fu rhyngddynt a'i cydwladwyr yno.
      </lb> 
      <lb n="5">Yn dyfod a ch&acirc;d luosog i Frydain ac yn 
      </lb>
      <lb n="5-6">gwenwyno
      </lb>
      <lb n="6">
      &nbsp;Uthr ben-dragon. Y modd y c&acirc;s Arthur
      </lb> 
      <lb n="7">y Goron. Ychydig hanes a'm ei weithredoedd. Y
      </lb> 
      <lb n="8">Saeson yn goresgyn Lloegr wedi marwolaeth
      </lb> 
      <lb n="9">Arthur. Tywysogion Cymru. Ychydigyn o 
      </lb>
      <lb n="9-10">gyfraith
      </lb>
      <lb n="10">
      &nbsp;Howel-dda. Yr amser y daethant i 
      </lb>
      <lb n="10-11">ufuddhau
      </lb>
      <lb n="11">
       Cyfraith Loegr.
      
      
      
      
      </lb> 
      <lb n="12">WEdi dangos eusys i ba gyflyrau 
      </lb>
      <lb n="12-13">gresynol
      </lb>
      <lb n="13">
       y dycpwyd ein Hynafiaid gan
      </lb> 
      <lb n="14">y llofrudd-enaid hwnnw PECHOD,
      </lb> 
      <lb n="15">bellach mi a &acirc;f rhagof i ddangos eu
      </lb> 
      <lb n="16">hynfydrwydd di-gymmar wrth
      </lb> 
      <lb n="17">ddeisyf porth gan y Saeson. Etto
      </lb> 
      <lb n="18">nid oedd hyn onid y peth y mae Duw yn fwgwth
      </lb> 
      <lb n="19">yn erbyn anufudd-dod. Oni wrandewi a'r lais yr
      </lb> 
      <lb n="20">Arglwydd dy Dduw, Yr Arglwydd a'th dery di
      </lb> 
      <lb n="21">ag ynfydrwydd, ac a dallineb, ac a syndod calon.
      </lb> 
      <lb n="22">Deut. 28, 15, 28. Ofnasant y Saeson o'r blaen
      </lb> 
      <lb n="23">yn fwy nag angau ei hun. Etto dallwyd hwy yn y
      </lb> 
      <lb n="24">cyfryw fodd, fel y danfonasant gennadon attynt, i'w
      </lb> 
      <lb n="25">gwahawdd hwy trosodd. Mae etto beth anghyttundeb
      </lb> 
      <lb n="26">ym mysc Historiawyr am ba achos y galwyd y Saeson
      </lb> 
      <lb n="27">yma gyntaf. 1, Rhai a ddywedant ddarfod eu galw
      </lb> 
      <lb n="28">yn borth yn erbyn y Ffichtiaid, a hyn sydd 
      </lb>
      <lb n="28-29">debyccaf
      </lb>
      <lb n="29">
       i fod yn wirionedd, gan nad yw Gildas ei hun
      
      
      </lb>
      </pb>
      <pb n="66.">
      
      
       
      <lb n="1">yn crybwyll am un achos arall. 2. Eraill a
      </lb> 
      <lb n="2">ddywedant fod Amgylchiadau y Brutaniaid fal hyn
      </lb> 
      <lb n="3">y pryd hwnnw. Fe ddescynnodd Coron y 
      </lb>
      <lb n="3-4">Deyrnas
      </lb>
      <lb n="4">
       i wr graslawn a elwid Constans, yr hwn a
      </lb> 
      <lb n="5">ddycpwyd i fynu mywn Monachlog, ac o'r achos
      </lb> 
      <lb n="6">hwnnw, yr oedd ef yn anghydnabyddus ag 
      </lb>
      <lb n="6-7">arferion
      </lb>
      <lb n="7">
       y Ll&#375;s, a'r gyfraith wladol. Felly efe a
      </lb> 
      <lb n="8">osododd Ddistain, neu oruchel Stiwart tano i
      </lb> 
      <lb n="9">lywodraethu'r Deyrnas. Y Distain hwnnw a 
      </lb>
      <lb n="9-10">elwid
      </lb>
      <lb n="10">
      &nbsp;Gwrtheyrn, a dyn balch, rhodresgar aniwair
      </lb> 
      <lb n="11">oedd efe. A gwedi cael awdurdod brenhinawl
      </lb> 
      <lb n="12">yn ei law, efe a feddyliodd ladd ei feistir. Felly
      </lb> 
      <lb n="13">efe a roddes aur ac arian i ryw ysgerbydiaid ofer,
      </lb> 
      <lb n="14">a'r iddynt ruthro am ben ystafell y Brenhin a'i
      </lb> 
      <lb n="15">ladd ef. Ac yn ddiattreg hwy a aethant, ac a 
      </lb>
      <lb n="15-16">waeddasant
      </lb>
      <lb n="16">
       hyd yr heolydd, Gwrtheyrn Sydd
      </lb> 
      <lb n="17">Frenin Teilwng o deyrn-wialen ynys
      </lb> 
      <lb n="18">Brydain, a Chonstans Sydd 
      </lb>
      <lb n="18-19">Anheilwng.
      </lb>
      <lb n="19">
       Ac yn ddianoed cychwyn a 
      </lb>
      <lb n="19-20">wnaethant
      </lb>
      <lb n="20">
       a'm ben ystafell y Brenin, a'i ladd a 
      </lb>
      <lb n="20-21">orugant,
      </lb>
      <lb n="21">
       a dwyn eu ben ger bron Gwrtheyrn. A
      </lb> 
      <lb n="22">phan welodd ef hynny, tristau megis wylaw a
      </lb> 
      <lb n="23">wnaeth, ac eusys ni bu erioed lawenach yn ei galon.
      </lb> 
      <lb n="24">A gwedi ei eneinio ef yn Frenin, efe a 
      </lb>
      <lb n="24-25">alwodd
      </lb>
      <lb n="25">
       y Saeson atto, rhac i gyfnesyfiaid Constans
      </lb> 
      <lb n="26">ymddial arno: Ond nid yw hyn wirionedd, gan
      </lb> 
      <lb n="27">na bu Constans erioed yn Frenin ym Mhrydain,
      
      
      </lb>
      </pb>
      <pb n="67.">
      
      
       
      <lb n="1">can's efe a laddwyd yn yr Ital. 3. Eraill a
      </lb> 
      <lb n="2">ddywedant fod Amgylchiadau Gwrtheyrn fal hyn.
      </lb> 
      <lb n="3">Ni bu dim trefn neu lywodraeth weddaidd ym
      </lb> 
      <lb n="4">mysc y Brutaniaid wedi'r Rhufeiniaid ddilyssu'r
      </lb> 
      <lb n="5">deyrnged iddynt. Eneinid Brenin heddyw, ac a'i 
      </lb>
      <lb n="5-6">difreinid
      </lb>
      <lb n="6">
       ysgatfydd yr ail ddiwrnod, a dewisid un arall
      </lb> 
      <lb n="7">yn ei le: Ac y mae'n ddiddadl eu bod yn 
      </lb>
      <lb n="7-8">anwadalfarn
      </lb>
      <lb n="8">
       jawn yn eu llywodraeth, canys y mae Gildas
      </lb> 
      <lb n="9">(y Brittwn dysgedig hwnnw) yn siccrhau hynny.
      </lb> 
      <lb n="10">Ac yno Gwrtheyrn (rhac y gwneid yr un castiau
      </lb> 
      <lb n="11">ag ynteu) a fwriadodd i siccrhau ei orseddfaingc
      </lb> 
      <lb n="12">yn gadarn fal y tygasai ef. Felly efe a alwodd
      </lb> 
      <lb n="13">a'm y Saeson i amddiffyn ei goron, os cynnygid ei
      </lb> 
      <lb n="14">ddifreinio ef. Hyn a allai fod yn ddiau yn
      </lb> 
      <lb n="15">beth achlysur, ond i ymladd a'r Ffichtiaid oedd
      </lb> 
      <lb n="16">y prif ddiben i alw'r Saeson i Frydain, can's nid
      </lb> 
      <lb n="17">yw Gildas (fal y dywedais eusys) yn crybwyll
      </lb> 
      <lb n="18">am un achos arall.
      
      
      
      </lb> 
      <lb n="19">Felly Gwrtheyrn a alwodd ei ben-cynghoriaid
      </lb> 
      <lb n="20">a'i Uchel-Swyddogion atto, a gwedi eu dyfod, efe
      </lb> 
      <lb n="21">a dywedodd wrthynt fal hyn, " Chwi wyddoch
      </lb> 
      <lb n="22">f'Arglwyddi fod y Rhufeiniaid wedi ein 
      </lb>
      <lb n="22-23">gommedd
      </lb>
      <lb n="23">
       er ys talm, a ninnau yn llwyr anigonol i
      </lb> 
      <lb n="24">roddi c&acirc;d a'r faes i'n gelynion, ynteu 
      </lb>
      <lb n="24-25">anghenrheidiol
      </lb>
      <lb n="25">
       ydyw i ni ddanfon at ryw genedl a'm
      </lb> 
      <lb n="26">borth. Ac yr ydwyf fi yn barnu fod y Saeson
      </lb> 
      <lb n="27">yn bobl wychr, lewion, galonnog. Ac os bydd
      </lb> 
      <lb n="28">gwiw ganddynt i wneuthur ammod a ni, yr wyf
      </lb> 
      <lb n="29">yn gobeithio y bydd raid i'r Ffichtiaid
      </lb> 
      <lb n="30">a'r Scotiaid gymmeryd eu Coryglau tua'r 
      
      </lb>
      </pb>
      <pb n="67-68.">
      <lb n="30-1">Iwerddon
      </lb>
      </pb>
      <pb n="68.">
      <lb n="1">
       etto. (&#8225;), A hwy a attebasant gan
      </lb> 
      <lb n="2">ddywedyd, O Arglwydd frenin pwy all dy
